In [1]:
import tensorflow as tf
import tf2onnx
import numpy as np
import onnxruntime as ort
import os
from keras.models import load_model

In [2]:
model = load_model("./RNNVPWM.keras")
PWM=model.predict([[0]])

1/1 [==============================] - 0s 266ms/step


In [9]:
model.save("RNNVPWM")

INFO:tensorflow:Assets written to: RNNVPWM\assets


INFO:tensorflow:Assets written to: RNNVPWM\assets


In [4]:
input_signature = [tf.TensorSpec([1,1], tf.float32, name='x')]
onnx_model, _ = tf2onnx.convert.from_keras(model, input_signature, opset=13)

Could not search for non-variable resources. Concrete function internal representation may have changed.


In [3]:
os.system("python -m tf2onnx.convert --saved-model RNNVPWM --output RNNVPWM.onnx --opset 13")

0

In [11]:
os.getcwd()
PWM

array([[-0.00856168]], dtype=float32)

In [19]:
x_val = np.zeros((3,1,1), np.float32)
sess = ort.InferenceSession("RNNVPWM.onnx")
res = sess.run(None, {'simple_rnn_1_input': x_val})
print(res[0])

[[-0.00856168]
 [-0.00856168]
 [-0.00856168]]


In [17]:
x_val
#model.predict(x_val[0])

array([[[0.]]], dtype=float32)